name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: Typecheck (Node 18)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Cache TS build info
        uses: actions/cache@v4
        with:
          path: |
            **/*.tsbuildinfo
          key: ${{ runner.os }}-tsbuildinfo-18-${{ hashFiles('**/tsconfig*.json') }}-${{ hashFiles('package-lock.json') }}
      - run: npm run typecheck

  lint:
    name: Lint (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: [typecheck]
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run lint

  test:
    name: Test (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: [typecheck]
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm test --silent

  build:
    name: Build (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: [typecheck, lint, test]
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - name: Cache TS build info
        uses: actions/cache@v4
        with:
          path: |
            **/*.tsbuildinfo
          key: ${{ runner.os }}-tsbuildinfo-${{ matrix.node }}-${{ hashFiles('**/tsconfig*.json') }}-${{ hashFiles('package-lock.json') }}
      - run: npm run build
      - name: Upload backend dist
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: apps/backend/dist
      - name: Upload mobile dist
        uses: actions/upload-artifact@v4
        with:
          name: mobile-dist
          path: apps/mobile/dist


